# Generated by Django 4.2 on 2023-04-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='ending_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='loan',
            name='starting_date',
            field=models.DateField(),
        ),
    ]
